server:
  port: 8090
spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/mybatis
      username: root
      password: admin
      driverClassName: com.mysql.jdbc.Driver

#spring:
#  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/shopping
#      username: root
#      password: admin