server:
  port: 8090

spring:
  datasource:
    db1:
     driver-class-name: com.mysql.jdbc.Driver
     jdbc-url: jdbc:mysql://127.0.0.1:3306/mybatis #?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
     username: root
     password: admin
    db2:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test #?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: admin

##mybatis.config-location=classpath:mybatis-config.xml
#mybatis:
#  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
#  type-aliases-package: com.zyh.model
  #  用来定义SQL语句文件的位置。
  #  用来定义domain包的位置
#    config-location: classpath:mybatis-config.xml