#server:
#  port: 8090
food:
  meat: 烤肉
  rice: 拌饭
  flavor:
    - 咖喱味
    - 原味
    - 奥尔良味
#流式语法
#food: {meat: 烤肉 ,rice: 拌饭}

spring:
  profiles:
    active: dev
#开发环境
---
spring:
  profiles: dev

server:
  port: 8090

jasypt:
  encryptor:
    password: 123456!@#

info:
  username: ENC(/k0Ohi+ulwBZFSQnNnHjjg==)
  password: ENC(Y4FzSgKBF/0EnVVYr7deXg==)
---
#生产环境
spring:
  profiles: prod

server:
  port: 8010

jasypt:
  encryptor:
    password: 123456!@#

info:
  username: ENC(/k0Ohi+ulwBZFSQnNnHjjg==)
  password: ENC(Y4FzSgKBF/0EnVVYr7deXg==)